### ISSUE TITLE
Need PfUnit built on Derecho and added to  intel_derecho.cmake

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/ccs_config_cesm#131]
In order to run FORTRAN unit-testing on Derecho we need a version of the library built there as well as the path for it added to the intel_derecho.cmake file under machines.

The Cheyenne version has this:

``` cmake
if (MPILIB STREQUAL mpi-serial AND NOT compile_threaded)
  set(PFUNIT_PATH "$ENV{CESMDATAROOT}/tools/pFUnit/pFUnit4.7.0_cheyenne_Intel19.1.1_noMPI_noOpenMP")
endif()
```

Something like that needs to be done, including building the PFUnit library for version 4.7.0.

@billsacks it looks like you were involved in this before. Is this something that you can do?

**Comment by billsacks** [comment]
@jedwards4b 's question about whether there's a spack package for pFUnit inspired me to double check, and I found that there actually is a pfunit spack package: Before I had just looked via a google search and didn't find anything, but @jedwards4b 's question inspired me to look more closely and I discovered [that there is](https://packages.spack.io/package.html?name=pfunit). @jedwards4b - What's your experience in terms of the best way for us to get that installed? Ask via help@ucar.edu? Do it ourselves? I've only done a bit with spack myself, but am happy to learn - but would love to hear from you what general approach would be best here.

**Comment by jedwards4b** [comment]
I installed pfunit using the gnu compiler, but that won't work with the default intel compiler on derecho because of the 
fortran module files.   I was unable to install with intel, I think that this is due to a bug in the pfunit spack file.  @billsacks will try installing outside of spack today.   I also tried using the gnu compiler for unit tests but there appears to be a bug in test_sys_unittest.py as it ignores the --compiler option to scripts_regression_tests.py
