### ISSUE TITLE
Bug in Depends.nvhpc

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/ccs_config_cesm#175]
In cam6_4_001 submodule clubb clubb_4ncar_20231115_5406350
contains file clubb/src/CLUBB_core/mt95.f90   (Note the f90 not F90)

The rule in Depends.nvhpc applies to .F90 sources and so a new rule needs to
be created which applies to .f90 files.

**Comment by sjsprecious** [comment]
Thanks Jim for identifying this issue. This problem is fixed in the latest CLUBB tag (`clubb_4ncar_20240605_73d60f6`, https://github.com/larson-group/clubb_release/tree/clubb_4ncar_20240605_73d60f6/src/CLUBB_core) and will be brought into CAM later to address this Github issue (https://github.com/ESCOMP/CAM/issues/1036).

**Comment by sjsprecious** [comment]
fixed by https://github.com/ESCOMP/CAM/pull/1086
